import math
import string
import re
import itertools

def issorted(array):
    return array == tuple(sorted(list(array))) and len(set(tuple(sorted(list(array))))) != 1

def isunique(array):
    return array == tuple(set(array))

class Lottery:
    def sortByOdds(self, rules):
        scores = {}
        for rule in rules:
#            print(rule)
            m = re.search("(.*?)\:\s(\d*?)\s(\d*?)\s(\w*?)\s(\w*)", rule)
            rule = m.group(1)
            max_range = m.group(2)
            pick_num = m.group(3)
            sort_flag = m.group(4)
            unique_flag = m.group(5)
            print(rule,max_range,pick_num,sort_flag,unique_flag) 
            scores[rule] = self.get_score(int(max_range),int(pick_num),sort_flag,unique_flag)
            print(scores[rule])

        result=[]
        for k, v in sorted(scores.items(), key=lambda x:x[1]):
            result.append(k)
        return tuple(result)


    def get_score(self,max_range,pick_num,sort_flag,unique_flag):
        all_list = list(itertools.product(range(1,max_range+1), repeat=pick_num))
        if sort_flag   == 'T':
            all_list = filter(issorted,all_list)
        print(all_list)
        if unique_flag == 'T':
            all_list = filter(isunique,all_list)
        print(all_list)
        return len(all_list)

# BEGIN KAWIGIEDIT TESTING
# Generated by KawigiEdit-pfx 2.1.9
import sys
import time
def KawigiEdit_RunTest(testNum, p0, hasAnswer, p1):
	sys.stdout.write(str("Test ") + str(testNum) + str(": [") + str("{"))
	for i in range(len(p0)):
		if (i > 0):
			sys.stdout.write(str(","))
		
		sys.stdout.write(str("\"") + str(p0[i]) + str("\""))
	
	sys.stdout.write(str("}"))
	print(str("]"))
	obj = Lottery()
	startTime = time.clock()
	answer = obj.sortByOdds(p0)
	endTime = time.clock()
	res = True
	print(str("Time: ") + str((endTime - startTime)) + str(" seconds"))
	if (hasAnswer):
		print(str("Desired answer:"))
		sys.stdout.write(str("\t") + str("{"))
		for i in range(len(p1)):
			if (i > 0):
				sys.stdout.write(str(","))
			
			sys.stdout.write(str("\"") + str(p1[i]) + str("\""))
		
		print(str("}"))
	
	print(str("Your answer:"))
	sys.stdout.write(str("\t") + str("{"))
	for i in range(len(answer)):
		if (i > 0):
			sys.stdout.write(str(","))
		
		sys.stdout.write(str("\"") + str(answer[i]) + str("\""))
	
	print(str("}"))
	if (hasAnswer):
		if (len(answer) != len(p1)):
			res = False
		else:
			for i in range(len(answer)):
				if (answer[i] != p1[i]):
					res = False
				
			
		
	
	if (not res):
		print(str("DOESN'T MATCH!!!!"))
	elif ((endTime - startTime) >= 2):
		print(str("FAIL the timeout"))
		res = False
	elif (hasAnswer):
		print(str("Match :-)"))
	else:
		print(str("OK, but is it right?"))
	
	print(str(""))
	return res

all_right = True


# ----- test 0 -----
p0 = ["PICK ANY TWO: 10 2 F F","PICK TWO IN ORDER: 10 2 T F","PICK TWO DIFFERENT: 10 2 F T","PICK TWO LIMITED: 10 2 T T"]
p1 = ["PICK TWO LIMITED","PICK TWO IN ORDER","PICK TWO DIFFERENT","PICK ANY TWO"]
all_right = KawigiEdit_RunTest(0, p0, True, p1) and all_right
# ------------------

# ----- test 1 -----
p0 = ["INDIGO: 93 8 T F","ORANGE: 29 8 F T","VIOLET: 76 6 F F","BLUE: 100 8 T T","RED: 99 8 T T","GREEN: 78 6 F T","YELLOW: 75 6 F F"]
p1 = ["RED","ORANGE","YELLOW","GREEN","BLUE","INDIGO","VIOLET"]
all_right = KawigiEdit_RunTest(1, p0, True, p1) and all_right
# ------------------

# ----- test 2 -----
p0 = []
p1 = []
all_right = KawigiEdit_RunTest(2, p0, True, p1) and all_right
# ------------------

if (all_right):
	print(str("You're a stud (at least on the example cases)!"))
else:
	print(str("Some of the test cases had errors."))

# PROBLEM STATEMENT
# In most states, gamblers can choose from a wide variety of different lottery games.  The rules of a lottery are defined by two integers (choices and blanks) and two boolean variables (sorted and unique).  choices represents the highest valid number that you may use on your lottery ticket.  (All integers between 1 and choices, inclusive, are valid and can appear on your ticket.)  blanks represents the number of spots on your ticket where numbers can be written.
# 
# The sorted and unique variables indicate restrictions on the tickets you can create.  If sorted is set to true, then the numbers on your ticket must be written in non-descending order.  If sorted is set to false, then the numbers may be written in any order.  Likewise, if unique is set to true, then each number you write on your ticket must be distinct.  If unique is set to false, then repeats are allowed.
# 
# Here are some example lottery tickets, where choices = 15 and blanks = 4:
# {3, 7, 12, 14} -- this ticket is unconditionally valid.
# {13, 4, 1, 9} -- because the numbers are not in nondescending order, this ticket is valid only if sorted = false.
# {8, 8, 8, 15} -- because there are repeated numbers, this ticket is valid only if unique = false.
# {11, 6, 2, 6} -- this ticket is valid only if sorted = false and unique = false.
# 
# Given a list of lotteries and their corresponding rules, return a list of lottery names sorted by how easy they are to win.  The probability that you will win a lottery is equal to (1 / (number of valid lottery tickets for that game)).  The easiest lottery to win should appear at the front of the list.  Ties should be broken alphabetically (see example 1).
# 
# DEFINITION
# Class:Lottery
# Method:sortByOdds
# Parameters:tuple (string)
# Returns:tuple (string)
# Method signature:def sortByOdds(self, rules):
# 
# 
# CONSTRAINTS
# -rules will contain between 0 and 50 elements, inclusive.
# -Each element of rules will contain between 11 and 50 characters, inclusive.
# -Each element of rules will be in the format "<NAME>:_<CHOICES>_<BLANKS>_<SORTED>_<UNIQUE>" (quotes for clarity). The underscore character represents exactly one space. The string will have no leading or trailing spaces.
# -<NAME> will contain between 1 and 40 characters, inclusive, and will consist of only uppercase letters ('A'-'Z') and spaces (' '), with no leading or trailing spaces.
# -<CHOICES> will be an integer between 10 and 100, inclusive, with no leading zeroes.
# -<BLANKS> will be an integer between 1 and 8, inclusive, with no leading zeroes.
# -<SORTED> will be either 'T' (true) or 'F' (false).
# -<UNIQUE> will be either 'T' (true) or 'F' (false).
# -No two elements in rules will have the same name.
# 
# 
# EXAMPLES
# 
# 0)
# {"PICK ANY TWO: 10 2 F F"
# ,"PICK TWO IN ORDER: 10 2 T F"
# ,"PICK TWO DIFFERENT: 10 2 F T"
# ,"PICK TWO LIMITED: 10 2 T T"}
# 
# Returns: { "PICK TWO LIMITED",  "PICK TWO IN ORDER",  "PICK TWO DIFFERENT",  "PICK ANY TWO" }
# 
# The "PICK ANY TWO" game lets either blank be a number from 1 to 10.  Therefore, there are 10 * 10 = 100 possible tickets, and your odds of winning are 1/100.
# 
# The "PICK TWO IN ORDER" game means that the first number cannot be greater than the second number.  This eliminates 45 possible tickets, leaving us with 55 valid ones.  The odds of winning are 1/55.
# 
# The "PICK TWO DIFFERENT" game only disallows tickets where the first and second numbers are the same.  There are 10 such tickets, leaving the odds of winning at 1/90.
# 
# Finally, the "PICK TWO LIMITED" game disallows an additional 10 tickets from the 45 disallowed in "PICK TWO IN ORDER".  The odds of winning this game are 1/45.
# 
# 1)
# {"INDIGO: 93 8 T F",
#  "ORANGE: 29 8 F T",
#  "VIOLET: 76 6 F F",
#  "BLUE: 100 8 T T",
#  "RED: 99 8 T T",
#  "GREEN: 78 6 F T",
#  "YELLOW: 75 6 F F"}
# 
# 
# Returns: { "RED",  "ORANGE",  "YELLOW",  "GREEN",  "BLUE",  "INDIGO",  "VIOLET" }
# 
# Note that INDIGO and BLUE both have the exact same odds (1/186087894300).  BLUE is listed first because it comes before INDIGO alphabetically.
# 
# 2)
# {}
# 
# Returns: { }
# 
# Empty case
# 
# END KAWIGIEDIT TESTING
#Powered by KawigiEdit-pfx 2.1.9!
